[supervisord]
nodaemon=true
user=root

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true

[program:yii-queue]
command=php /var/www/html/yii queue/listen --verbose=1 --color=0
autostart=true
autorestart=true
stderr_logfile=/var/www/html/runtime/queue-error.log
stdout_logfile=/var/www/html/runtime/queue-out.log

[program:cron]
command=cron -f
autostart=true
autorestart=true
