#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/config/env.php';

if (!app_is_railway() && class_exists(\Dotenv\Dotenv::class) && file_exists(__DIR__ . '/.env')) {
    \Dotenv\Dotenv::createUnsafeImmutable(__DIR__)->safeLoad();
}

defined('YII_DEBUG') or define('YII_DEBUG', app_env_bool('YII_DEBUG', false));
defined('YII_ENV') or define('YII_ENV', app_env('YII_ENV', 'prod'));

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
